fix: new script run phpcs

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -1,35 +1,43 @@
 #!/bin/sh
 
-PROJECT=`php -r "echo dirname(dirname(dirname(realpath('$0'))));"`
-STAGED_FILES_CMD=`git diff --cached --name-only --diff-filter=ACMR HEAD | grep \\\\.php`
+STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".php\{0,1\}$")
 
-# Determine if a file list is passed
-if [[ "$#" -eq 1 ]]
-then
-    oIFS=$IFS
-    IFS='
-    '
-    SFILES="$1"
-    IFS=$oIFS
+if [[ "$STAGED_FILES" = "" ]]; then
+  exit 0
 fi
-SFILES=${SFILES:-$STAGED_FILES_CMD}
 
-echo "Checking PHP Lint..."
-for FILE in $SFILES
+PASS=true
+
+echo "\nValidating PHPCS:\n"
+
+# Check for phpcs
+which ./vendor/bin/phpcs &> /dev/null
+if [[ "$?" == 1 ]]; then
+  echo "\t\033[41mPlease install PHPCS\033[0m"
+  exit 1
+fi
+
+RULESET=./phpcs.xml
+
+for FILE in $STAGED_FILES
 do
-    php -l -d display_errors=0 $PROJECT/$FILE
-    if [[ $? != 0 ]]
-    then
-        echo "Fix the error before commit."
-        exit 1
-    fi
-    FILES="$FILES $PROJECT/$FILE"
+  ./vendor/bin/phpcs --standard="$RULESET" "$FILE"
+
+  if [[ "$?" == 0 ]]; then
+    echo "\t\033[32mPHPCS Passed: $FILE\033[0m"
+  else
+    echo "\t\033[41mPHPCS Failed: $FILE\033[0m"
+    PASS=false
+  fi
 done
 
-if [[ "$FILES" != "" ]]
-then
-    echo "Running Code Sniffer. Code standard PSR2."
-    php ./hooks/phpcs.phar --standard=PSR2 --encoding=utf-8 -n -p $FILES
+echo "\nPHPCS validation completed!\n"
+
+if ! $PASS; then
+  echo "\033[41mCOMMIT FAILED:\033[0m Your commit contains files that should pass PHPCS but do not. Please fix the PHPCS errors and try again.\n"
+  exit 1
+else
+  echo "\033[42mCOMMIT SUCCEEDED\033[0m\n"
 fi
 
 exit $?
